LANGUAGES = {
    'English': {
        'title': 'SMC Trading Dashboard',
        'settings': 'Settings',
        'language': 'Language',
        'category': 'Category',
        'pair': 'Pair',
        'timeframe': 'Timeframe',
        'risk': 'Risk %',
        'refresh': 'Refresh',
        'signal': 'Signal',
        'trade_levels': 'Trade Levels',
        'entry': 'ENTRY',
        'sl': 'STOP LOSS',
        'tp': 'TAKE PROFIT',
        'buy': 'BUY',
        'sell': 'SELL',
        'neutral': 'NEUTRAL',
        'chart': 'Chart',
        'trade_manager': 'Trade Manager',
        'open_trade': 'Open Trade',
        'save_csv': 'Save CSV',
        'close_all': 'Close All',
        'total': 'Total',
        'open': 'Open',
        'win_rate': 'Win Rate',
        'pnl': 'PnL',
        'news': 'Market News',
        'backtest': 'Backtesting',
        'run_backtest': 'Run Backtest',
        'welcome': 'Welcome',
        'logout': 'Logout',
        'email': 'Email',
        'license': 'License Key',
        'verify': 'Verify License',
        'active': 'Active',
        'inactive': 'Inactive',
        'disclaimer': '⚠️ DISCLAIMER: This tool is for educational purposes only. All analysis provided is not financial advice. The developer (Wail) is not responsible for any investment decisions made based on this tool.',
        'bos': 'Break of Structure',
        'choch': 'Change of Character',
        'ob': 'Order Block',
        'fvg': 'Fair Value Gap',
        'mtf': 'Multi-Timeframe Analysis',
        'lot_size': 'Lot Size',
        'account_size': 'Account Size ($)',
        'price': 'Price',
        'high': 'High 24h',
        'low': 'Low 24h',
        'change': 'Change',
    },
    'العربية': {
        'title': 'لوحة تداول SMC',
        'settings': 'الإعدادات',
        'language': 'اللغة',
        'category': 'الفئة',
        'pair': 'الزوج',
        'timeframe': 'الإطار الزمني',
        'risk': 'نسبة المخاطرة %',
        'refresh': 'تحديث',
        'signal': 'إشارة التداول',
        'trade_levels': 'مستويات الصفقة',
        'entry': 'الدخول',
        'sl': 'وقف الخسارة',
        'tp': 'جني الأرباح',
        'buy': 'شراء',
        'sell': 'بيع',
        'neutral': 'محايد',
        'chart': 'الرسم البياني',
        'trade_manager': 'إدارة الصفقات',
        'open_trade': 'فتح صفقة',
        'save_csv': 'حفظ CSV',
        'close_all': 'إغلاق الكل',
        'total': 'الإجمالي',
        'open': 'مفتوحة',
        'win_rate': 'نسبة الفوز',
        'pnl': 'الربح/الخسارة',
        'news': 'أخبار السوق',
        'backtest': 'الاختبار التاريخي',
        'run_backtest': 'تشغيل الاختبار',
        'welcome': 'مرحباً',
        'logout': 'خروج',
        'email': 'البريد الإلكتروني',
        'license': 'مفتاح الترخيص',
        'verify': 'التحقق من الترخيص',
        'active': 'نشط',
        'inactive': 'غير نشط',
        'disclaimer': '⚠️ إخلاء مسؤولية: هذه الأداة للأغراض التعليمية فقط. التحليلات المقدمة ليست نصيحة مالية. المطور (وائل) غير مسؤول عن أي قرارات استثمارية.',
        'bos': 'كسر البنية',
        'choch': 'تغيير الطابع',
        'ob': 'كتلة الأوامر',
        'fvg': 'الفجوة السعرية',
        'mtf': 'تحليل متعدد الأطر',
        'lot_size': 'حجم اللوت',
        'account_size': 'حجم الحساب ($)',
        'price': 'السعر',
        'high': 'أعلى 24س',
        'low': 'أدنى 24س',
        'change': 'التغيير',
    },
    'Français': {
        'title': 'Tableau de Bord SMC',
        'settings': 'Paramètres',
        'language': 'Langue',
        'category': 'Catégorie',
        'pair': 'Paire',
        'timeframe': 'Période',
        'risk': 'Risque %',
        'refresh': 'Actualiser',
        'signal': 'Signal',
        'trade_levels': 'Niveaux',
        'entry': 'ENTRÉE',
        'sl': 'STOP LOSS',
        'tp': 'TAKE PROFIT',
        'buy': 'ACHETER',
        'sell': 'VENDRE',
        'neutral': 'NEUTRE',
        'chart': 'Graphique',
        'trade_manager': 'Gestion',
        'open_trade': 'Ouvrir',
        'save_csv': 'Sauvegarder',
        'close_all': 'Tout Fermer',
        'total': 'Total',
        'open': 'Ouvert',
        'win_rate': 'Taux Victoire',
        'pnl': 'PnL',
        'news': 'Actualités',
        'backtest': 'Backtesting',
        'run_backtest': 'Lancer',
        'welcome': 'Bienvenue',
        'logout': 'Déconnexion',
        'email': 'Email',
        'license': 'Clé de Licence',
        'verify': 'Vérifier',
        'active': 'Actif',
        'inactive': 'Inactif',
        'disclaimer': '⚠️ AVERTISSEMENT: Cet outil est à des fins éducatives uniquement. Les analyses ne constituent pas des conseils financiers. Le développeur (Wail) décline toute responsabilité.',
        'bos': 'Rupture de Structure',
        'choch': 'Changement de Caractère',
        'ob': "Bloc d'Ordres",
        'fvg': 'Écart de Valeur',
        'mtf': 'Analyse Multi-Temporelle',
        'lot_size': 'Taille du Lot',
        'account_size': 'Taille du Compte ($)',
        'price': 'Prix',
        'high': 'Haut 24h',
        'low': 'Bas 24h',
        'change': 'Variation',
    },
    'Español': {
        'title': 'Panel SMC Trading',
        'settings': 'Configuración',
        'language': 'Idioma',
        'category': 'Categoría',
        'pair': 'Par',
        'timeframe': 'Marco Temporal',
        'risk': 'Riesgo %',
        'refresh': 'Actualizar',
        'signal': 'Señal',
        'trade_levels': 'Niveles',
        'entry': 'ENTRADA',
        'sl': 'STOP LOSS',
        'tp': 'TAKE PROFIT',
        'buy': 'COMPRAR',
        'sell': 'VENDER',
        'neutral': 'NEUTRAL',
        'chart': 'Gráfico',
        'trade_manager': 'Gestión',
        'open_trade': 'Abrir',
        'save_csv': 'Guardar CSV',
        'close_all': 'Cerrar Todo',
        'total': 'Total',
        'open': 'Abierto',
        'win_rate': 'Tasa Éxito',
        'pnl': 'PnL',
        'news': 'Noticias',
        'backtest': 'Backtesting',
        'run_backtest': 'Ejecutar',
        'welcome': 'Bienvenido',
        'logout': 'Cerrar Sesión',
        'email': 'Email',
        'license': 'Clave de Licencia',
        'verify': 'Verificar',
        'active': 'Activo',
        'inactive': 'Inactivo',
        'disclaimer': '⚠️ AVISO: Esta herramienta es solo para fines educativos. Los análisis no constituyen asesoramiento financiero. El desarrollador (Wail) no es responsable de ninguna decisión de inversión.',
        'bos': 'Ruptura de Estructura',
        'choch': 'Cambio de Carácter',
        'ob': 'Bloque de Órdenes',
        'fvg': 'Brecha de Valor',
        'mtf': 'Análisis Multi-Temporal',
        'lot_size': 'Tamaño del Lote',
        'account_size': 'Tamaño de Cuenta ($)',
        'price': 'Precio',
        'high': 'Máximo 24h',
        'low': 'Mínimo 24h',
        'change': 'Cambio',
    },
}

def get_text(lang, key):
    return LANGUAGES.get(lang, LANGUAGES['English']).get(key, key)